name: flutter_supabase_template
description: Flutter + Supabase auth sample with Riverpod and GoRouter
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.5.1
  go_router: ^16.2.4
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  shadcn_ui: ^0.43.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  riverpod_generator: ^2.5.1
  go_router_builder: ^3.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
